"""Grid + procedural path generation.

A map is a single winding 4-connected path from a spawn cell on the left edge
to the core cell on the right edge. Non-path cells are buildable. The path is
generated by a randomized depth-first search (self-avoiding) and accepted only
when its length falls inside a target band, which yields varied-but-fair maps.

The resulting :class:`GameMap` exposes the path both as a list of cells and as
a smooth polyline (cell centers) with a precomputed cumulative-length table so
enemies can be positioned by a single scalar ``dist`` along the path.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import List, Tuple

from .rng import Rng

Cell = Tuple[int, int]


@dataclass
class GameMap:
    width: int
    height: int
    path_cells: List[Cell]            # ordered spawn -> core
    polyline: List[Tuple[float, float]] = field(default_factory=list)  # cell centers
    cum_len: List[float] = field(default_factory=list)                 # cumulative dist
    buildable: set = field(default_factory=set)
    seed: int = 0

    @property
    def total_length(self) -> float:
        return self.cum_len[-1] if self.cum_len else 0.0

    @property
    def spawn(self) -> Cell:
        return self.path_cells[0]

    @property
    def core(self) -> Cell:
        return self.path_cells[-1]

    def pos_at(self, dist: float) -> Tuple[float, float]:
        """Interpolated (x, y) cell-coordinate at ``dist`` along the path."""
        cum = self.cum_len
        if dist <= 0:
            return self.polyline[0]
        if dist >= cum[-1]:
            return self.polyline[-1]
        # binary search for the segment containing ``dist``
        lo, hi = 0, len(cum) - 1
        while lo < hi:
            mid = (lo + hi) // 2
            if cum[mid] < dist:
                lo = mid + 1
            else:
                hi = mid
        i = max(1, lo)
        seg_start = cum[i - 1]
        seg_len = cum[i] - seg_start
        t = 0.0 if seg_len <= 0 else (dist - seg_start) / seg_len
        ax, ay = self.polyline[i - 1]
        bx, by = self.polyline[i]
        return (ax + (bx - ax) * t, ay + (by - ay) * t)

    def is_buildable(self, cx: int, cy: int) -> bool:
        return (cx, cy) in self.buildable


def _neighbors(cell: Cell, w: int, h: int):
    x, y = cell
    out = []
    if x + 1 < w:
        out.append((x + 1, y))
    if x - 1 >= 0:
        out.append((x - 1, y))
    if y + 1 < h:
        out.append((x, y + 1))
    if y - 1 >= 0:
        out.append((x, y - 1))
    return out


def _dfs_path(rng: Rng, w: int, h: int, start: Cell, goal: Cell,
              goal_bias: float) -> List[Cell] | None:
    """Randomized self-avoiding DFS from ``start`` to ``goal``.

    Neighbor order is shuffled but biased toward the goal by ``goal_bias`` so we
    still wander while reliably terminating. Returns the path or ``None``.
    """
    stack = [start]
    visited = {start}
    parent: dict[Cell, Cell] = {}
    while stack:
        cur = stack[-1]
        if cur == goal:
            # reconstruct
            path = [cur]
            while cur in parent:
                cur = parent[cur]
                path.append(cur)
            path.reverse()
            return path
        nbrs = [n for n in _neighbors(cur, w, h) if n not in visited]
        if not nbrs:
            stack.pop()
            continue
        # order neighbors: with prob goal_bias pick the one reducing distance,
        # otherwise random — produces winding paths that still reach the goal.
        def gdist(n: Cell) -> int:
            return abs(n[0] - goal[0]) + abs(n[1] - goal[1])

        if rng.chance(goal_bias):
            nbrs.sort(key=gdist)
            nxt = nbrs[0]
        else:
            nxt = rng.choice(nbrs)
        visited.add(nxt)
        parent[nxt] = cur
        stack.append(nxt)
    return None


def generate_map(seed: int, w: int, h: int,
                 min_len: int | None = None, max_len: int | None = None) -> GameMap:
    """Generate a winding path map. Retries until the path length is in band."""
    rng = Rng(seed).spawn_child(7)
    if min_len is None:
        min_len = int((w + h) * 1.4)
    if max_len is None:
        max_len = int(w * h * 0.42)

    best: List[Cell] | None = None
    for attempt in range(240):
        sy = rng.randint(1, h - 2)
        gy = rng.randint(1, h - 2)
        start = (0, sy)
        goal = (w - 1, gy)
        # lower goal_bias => windier path; vary per attempt for diversity
        bias = 0.30 + 0.45 * rng.random()
        path = _dfs_path(rng, w, h, start, goal, bias)
        if path is None:
            continue
        if min_len <= len(path) <= max_len:
            best = path
            break
        # remember a fallback that is at least long enough
        if best is None or (len(path) >= min_len and len(path) < len(best)):
            if len(path) >= min_len:
                best = path
            elif best is None:
                best = path

    if best is None:
        # extremely unlikely; degrade to a simple serpentine
        best = _serpentine(w, h)

    polyline = [(c[0] + 0.5, c[1] + 0.5) for c in best]
    cum = [0.0]
    for i in range(1, len(polyline)):
        ax, ay = polyline[i - 1]
        bx, by = polyline[i]
        cum.append(cum[-1] + math.hypot(bx - ax, by - ay))

    path_set = set(best)
    buildable = {(x, y) for x in range(w) for y in range(h) if (x, y) not in path_set}

    return GameMap(width=w, height=h, path_cells=best, polyline=polyline,
                   cum_len=cum, buildable=buildable, seed=seed)


def _serpentine(w: int, h: int) -> List[Cell]:
    """Deterministic fallback path (boustrophedon) guaranteeing connectivity."""
    cells: List[Cell] = []
    y = 1
    going_right = True
    while y < h - 1:
        cols = range(0, w) if going_right else range(w - 1, -1, -1)
        for x in cols:
            cells.append((x, y))
        going_right = not going_right
        y += 2
    return cells
